name: navinotes
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  provider: ^6.1.5
  dotted_decoration: ^2.0.0
  pdfx: ^2.9.1
  file_picker: ^10.1.9
  flutter_dotenv: ^5.2.1
  syncfusion_flutter_pdfviewer: ^29.2.7
  syncfusion_flutter_pdf: ^29.2.7+1
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  path_provider: ^2.1.5
  compdfkit_flutter: ^2.4.0+1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/images/boards/
    - assets/images/boards/notes/
    - assets/images/boards/create/
    - assets/images/boards/note_templates/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/inter/Inter-VariableFont_opsz,wght.ttf
