name: navinotes
description: "NaviNotes - Your smart notes app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  provider: ^6.1.5
  dotted_decoration: ^2.0.0
  pdfx: ^2.9.1
  file_picker: ^10.1.9
  flutter_dotenv: ^5.2.1
  syncfusion_flutter_pdfviewer: ^29.2.7
  syncfusion_flutter_pdf: ^29.2.7+1
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  path_provider: ^2.1.5
  compdfkit_flutter: ^2.4.0+1
  flutter_launcher_icons: ^0.14.3
  flutter_switch: ^0.3.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  mime: ^2.0.0
  http_parser: ^4.1.2
  email_validator: ^3.0.0
  logging: ^1.3.0
  fluttertoast: ^8.2.12
  google_sign_in: ^6.3.0
  firebase_auth: ^5.6.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_carousel_widget: ^3.1.0
  fl_chart: ^1.0.0
  flutter_quill: ^11.4.1
  data_table_2: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/images/boards/
    - assets/images/boards/dark_academia/
    - assets/images/boards/nature/
    - assets/images/boards/minimalist/
    - assets/images/boards/plain/
    - assets/images/boards/light_academia/
    - assets/images/del/
    - assets/images/boards/notes/
    - assets/images/boards/create/
    - assets/images/boards/note_templates/
    - assets/images/marketplace/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/static/Inter_18pt-Thin.ttf
          weight: 200
        - asset: assets/fonts/Inter/static/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/static/Inter_18pt-Black.ttf
          weight: 900
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/play_fair/static/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/play_fair/static/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/play_fair/static/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/play_fair/static/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/play_fair/static/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/play_fair/static/PlayfairDisplay-Black.ttf
          weight: 900
    - family: EB Garamond
      fonts:
        - asset: assets/fonts/EB_Garamond/EBGaramond-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/EB_Garamond/static/EBGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/EB_Garamond/static/EBGaramond-Medium.ttf
          weight: 500
        - asset: assets/fonts/EB_Garamond/static/EBGaramond-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EB_Garamond/static/EBGaramond-Bold.ttf
          weight: 700
        - asset: assets/fonts/EB_Garamond/static/EBGaramond-ExtraBold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: Crimson Pro
      fonts:
        - asset: assets/fonts/Crimson_Pro/CrimsonPro-VariableFont_wght.ttf
    - family: Crimson Text
      fonts:
        - asset: assets/fonts/Crimson_Text/CrimsonText-Regular.ttf
          weight: 400
        - asset: assets/fonts/Crimson_Text/CrimsonText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Crimson_Text/CrimsonText-Bold.ttf
          weight: 700
    - family: Libre Baskerville
      fonts:
        - asset: assets/fonts/Libre_Baskerville/LibreBaskerville-Regular.ttf
          weight: 400
        - asset: assets/fonts/Libre_Baskerville/LibreBaskerville-Bold.ttf
          weight: 600
